# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-12 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsName', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('goodsDesc', models.TextField(blank=True, verbose_name='内容')),
            ],
            options={
                'db_table': 'GoodsInfo',
            },
        ),
    ]
